### PR TITLE
[master] Update recipes to work with new version

### PR DESCRIPTION
**Pull request by dothanhtrung**
- Update package version.
- Support building with Docker.To start, simply run `make`

### CODE REVIEW

**Comment by zuka0828** [comment]
> I think that you may want to make PR which separates recipe update and addition of functions.

I think so too.
Now I always check all commits included in a PR one by one then merge them even if they are different types of update, so actually no serious problem for me.
However, formally, It might be better to split different kind of commits into multiple PRs to merge a part of them when some PRs take time to be confirmed.
Such kind of policies should be written in documents of meta-debian like `CONTRIBUTION.md`.

**Comment by zuka0828** [comment]
> I think that you should not put docker file and its related files in the meta-debian directory, you should create a docker directory and put it there.

Thank you for your opinion.
I would like to merge the all commits in this PR, then move Docker related files to `docker` sub directory in future commits.

**Comment by zuka0828** [comment]
@dothanhtrung Docker files have been moved to `docker` sub directory by 614183432786eedcfcb70c15b7504c386edcf1a0
Please make sure if the commit correctly updated the scripts.

**Comment by dothanhtrung** [comment]
Sorry for late reply, I had a Lunar New Year holiday last week.

> I think that you may want to make PR which separates recipe update and addition of functions.
Thank you for your suggestion. I will do that with next pull requests.

>> I think that you should not put docker file and its related files in the meta-debian directory, you should create a docker directory and put it there.
> @dothanhtrung Docker files have been moved to `docker` sub directory by [6141834](https://github.com/meta-debian/meta-debian/commit/614183432786eedcfcb70c15b7504c386edcf1a0)
> Please make sure if the commit correctly updated the scripts.
Thank you. I will check that commit and re-run the test.

**Comment by dothanhtrung** [comment]
I have checked the commit 6141834 and function for Docker works as expected.
Thank you for the update.

The test passed with poky:master `a7774ac`, as has been set in `docker/Makefile`,
and the pull request #127, which update `bison` and `mpfr` for new version.

**Pull request merged**
