### PR TITLE
busybox: Add ptest failures fix patches

### PR DESCRIPTION
**Pull request by masami256**
This PR contains 3 commits to fix test errors. 
Every commit added a patch name to SRC_URI variable because Poky has a patch. So it didn't needed to write a new patch to fix test errors.

The 0001-testsuite-check-uudecode-before-using-it.patch for tar command test , 0001-du-l-works-fix-to-use-145-instead-of-144.patch for du command test, and 0001-dc.tests-fix-two-test-case-to-also-depend-on-DC_BIG.patch for dc command test.

### CODE REVIEW

**Comment by zuka0828** [comment]
@masami256 Thank you for finding the patches.
We are now confirming the test results with the patches, then this PR would be merged.

**Comment by zuka0828** [comment]
@masami256 Regarding the second patch (`0001-du-l-works...`), we don't reproduce the same result (145) as yours. Did you get this result on a disk with 1KB block size?

I've confirmed the latest busybox (1.31.0) but the original patch has not been merged yet.
http://lists.busybox.net/pipermail/busybox/2018-November/086836.html
I would like to merge the second patch if we can reproduce the same result.

**Comment by masami256** [comment]
> @masami256 Regarding the second patch (`0001-du-l-works...`), we don't reproduce the same result (145) as yours. Did you get this result on a disk with 1KB block size?
> 

@zuka0828  Sorry for missing information . Yes. there is 1KB block size.
The du-l-works test depends on test environment so it's difficult to predict expectation result.

Can I remove commit  c205fcc from this pull request?

**Comment by zuka0828** [comment]
@masami256 Thank you for your confirmation!

>  The du-l-works test depends on test environment so it's difficult to predict expectation result.

I think so too.
At least, the result becomes 145 with 1KB block size disk like your environment.
Therefore, I guess 145 has to be required as the expected value, but unfortunately not yet in the upstream.

Also, we confirmed that the return value becomes 144 with QEMU environment.
In summary, we might need the both cases (144/145) as the expected values...

At the moment, it might be difficult to decide how we should treat the patch,
so could you remove the second patch from PR?
Regarding other pathces, we confirmed that the problems are solved by the patches,
so I would like to merge them.

**Comment by masami256** [comment]
@zuka0828 

Thank you for your reply!
I've removed  0001-du-l-works-fix-to-use-145-instead-of-144.patch from series of commits.
Would you mind re-check patches, please.

**Comment by zuka0828** [comment]
@masami256 I've merged the two patches, thank you.

**Pull request merged**
