### PR TITLE
dash: Add dash package

### PR DESCRIPTION
**Pull request by masami256**
This commit adds dash package which is contained in CIP's package list[1].
So, it'd be nice to have dash package in meta-debian.

Tested on deby-tiny(qemuarm64), that worked as expected.

```
 Debian GNU/Linux 10 192.168.7.2 /dev/ttyAMA0

 192.168.7.2 login: root

 The programs included with the Debian GNU/Linux system are free software;
 the exact distribution terms for each program are described in the
 individual files in /usr/share/doc/*/copyright.

 Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
 permitted by applicable law.
 login[1385]: root login on 'ttyAMA0'
 # echo $SHELL
 /bin/sh
 # ls -la /bin/sh
 lrwxrwxrwx    1 root     root             9 Oct 28 01:53 /bin/sh -> /bin/dash
```

Recipe is based on meta-openembedded's one[2].

1: https://gitlab.com/cip-project/cip-core/cip-pkglist/-/blob/master/pkglist_buster.yml
2:
http://cgit.openembedded.org/meta-openembedded/tree/meta-oe/recipes-shells/dash/dash_0.5.11.2.bb?h=master

### CODE REVIEW

**Comment by zuka0828** [comment]
@masami256 Thank you for adding dash to our repository!
The recipe sets `ALTERNATIVE_PRIORITY` to the same value (100) as bash.
I'm not sure the detailed specification about that variable, but does a conflict possibly happen when we install the both packages?

**Comment by masami256** [comment]
@zuka0828 Thank you for your comment!

I checked following cases.

```
IMAGE_INSTALL_append += "dash bash"
```
and
IMAGE_INSTALL_append += " bash dash"

I checked following cases. In the both cases dash was default shell. However, same priority will make conflused which going to be default.

From recipes, ALTERNATIVE_PRIORITY are set folloing values.

bash: 100
busybox: 50

If dash make to be default shell when user install dash by default, priority should be greator than bash.

I have following options...

1. dash's priority is greater than  bash
2. dash's priority is between busybox and bash
3. dash's priority is less than busybox

The option 1 makes dash as default shell. The other options  user is able to change priority by bbappend file. 

Debian use dash as /bin/sh, I think it's okay to have bigger priority than bash(e.g. 110). what do you think of?

**Comment by zuka0828** [comment]
@masami256 

> Debian use dash as /bin/sh, I think it's okay to have bigger priority than bash(e.g. 110). what do you think of?

I agree this point.
Also, thank you for your confirmation about the behavior when both dash & bash installed.
Could you increase the value of `ALTERNATIVE_PRIORITY`  then resend the patch?

**Comment by masami256** [comment]
@zuka0828 Thank you !

>  Could you increase the value of ALTERNATIVE_PRIORITY then resend the patch?

I updated the patch. I set ``` ALTERNATIVE_PRIORITY ``` to 110.

I confirmed that dash's priority set to 110 that is expected.

```
# cat /usr/lib/opkg/alternatives/sh
/bin/sh
/bin/bash.bash 100
/bin/busybox.nosuid 50
/bin/dash 110
```

Please take another look.

**Comment by zuka0828** [comment]
@masami256 Thanks! merged.

**Pull request merged**
