### PR TITLE
debian-package.bbclass: Fix wrong URL assembly for snapshot.d.o

### PR DESCRIPTION
**Pull request by hiraku-wfs**
The '/archive' is not necessary for JSON files.

### CODE REVIEW

**Comment by zuka0828** [comment]
@hiraku-wfs @iwamatsu  Thank you very much for your patch. I've confirmed that `DEBIAN_USE_SNAPSHOT = "1"` works.
Before trying the snapshot, we need to update the include files in `recipes-debian/sources` to apply the changes in `debian-source.bbclass`. This update will be merged to the `master` branch soon.

**Comment by hiraku-wfs** [comment]
@zuka0828 @iwamatsu Thank you very much for s.d.o support and merging my patch.

**Comment by zuka0828** [comment]
@hiraku-wfs I would like to inform that `recipes-debian/sources/*.inc` has been updated based on the latest `debian-source.bbclass` specification. Please try `DEBIAN_USE_SNAPSHOT = "1"` with the latest commit.

NOTE: "warrior" branch is the current development target. Please use warrior for the both poky and meta-debian instead of master according to the latest `README.md`

**Comment by hiraku-wfs** [comment]
@zuka0828 @iwamatsu Thank you very much! I checked that it works fine with the warrior branch.

By the way, I found that the snapshot.d.o server sometimes refuses parallel access. In such case, the following procedure might help us.

```
$ BB_NUMBER_PARSE_THREADS=1 BB_NUMBER_THREADS=1 bitbake core-image-minimal --runall="fetch"
$ bitbake core-image-minimal
```

**Comment by zuka0828** [comment]
@hiraku-wfs Thank you for the additional information.
Fetching all sources before building target is one of the solutions, but specifying the both `BB_NUMBER_PARSE_THREADS=1` and `BB_NUMBER_THREADS=1` takes time to fetch required sources.

Another solution is to use `lockfiles` flag to only lock the fetch task so that other tasks like unpack, configure, compile can be executed in parallel.
https://www.yoctoproject.org/docs/current/bitbake-user-manual/bitbake-user-manual.html#variable-flags
I'm not sure if it works as I guess, but It's worth trying.

**Pull request merged**
