### PR TITLE
aide: several tiny fixes for aide-common

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Comment by mctungnh** [comment]
In [2dccffc](https://github.com/meta-debian/meta-debian/pull/208/commits/2dccffc6df03834e35c1b4ee0a2aee38cd41eb7e), there is a comment "# 10_aide_hostname requires hostname command provided by net-tools." but I checked, the script's still worked without net-tools. On the other hand, command aide.wrapper of aide-common needs aide as RDEPENDS.

**Comment by yuwata** [comment]
Thank you for checking this PR.

10_aide_hostname requires hostname command with --fqdn option support. If I remember correctly, busybox's hostname command does not provide --fqdn option.

> On the other hand, command aide.wrapper of aide-common needs aide as RDEPENDS.

I will add that dependency. Thanks.

**Comment by yuwata** [comment]
@mctungnh Updated. PTAL.

**Comment by mctungnh** [comment]
> 10_aide_hostname requires hostname command with --fqdn option support. If I remember correctly, busybox's hostname command does not provide --fqdn option.

I checked. It's OK.

> I will add that dependency. Thanks.

Thanks.

**Comment by zuka0828** [comment]
@yuwata @mctungnh Thank you for creating the patches and refining!

I would like to merge all commits in this PR.

**Pull request merged**
