### PR TITLE
[warrior] Update source code version

### PR DESCRIPTION
**Pull request by dothanhtrung**
- openssl: Update to 1.1.1d-0+deb10u3.
- qemu: Update to 3.1+dfsg-8+deb10u5.
- gnutls: Update to 3.6.7-4+deb10u3.
- git: Update to 2.20.1-2+deb10u3.
- curl: Update to 7.64.0-4+deb10u1.
- base-files: Update to 10.3+deb10u4.
- tzdata: Update to 2020a-0+deb10u1.

### CODE REVIEW

**Comment by 0xDen** [comment]
Hi.
Is it possible to speed up the review of this pull request since we're waiting new updates for our build system based on Yocto.
Due to this issue we cannot go on and build our images.
Thanks.

**Comment by mozoko** [comment]
Hi, I tried building deby as written [here.](https://github.com/meta-debian/meta-debian#setup-build-environment) with this PR commits.
I checked that deby was built without any probrem and could boot it on qemu.

On building, I added below to local.conf
```
MACHINE = "qemuarm"

IMAGE_INSTALL_append = " \
    openssl \
    qemu \
    gnutls \
    git \
    curl \
    tzdata \
"
```
and change meta/conf/bitbake.conf like this.
```
-INITRAMFS_MAXSIZE ??= "131072"
+INITRAMFS_MAXSIZE ??= "262144"
```

**Comment by mozoko** [comment]
>Hi, I tried building deby as written here. 
Sorry, this is wrong.
The build image is deby-tiny, not deby.

**Comment by hiraku-wfs** [comment]
@mozoko The deby-tiny is not an image name but distro name.
I think core-image-minimal is the image which you have built . And you built the image with  DISTRO=deby-tiny config.

**Comment by mozoko** [comment]
@hiraku-wfs 
> The deby-tiny is not an image name but distro name.

Sorry, that is my mistake.

@0xDen 
So, I built the image with DISTRO=deby-tiny config not DISTRO=deby without any problem.
I'm sorry for confusing you.

**Pull request merged**
